---
- hosts: ubuntu
  become: yes
  gather_facts: yes

  tasks:

  - name: Check the PHP version which is currently installed on the server
    shell: php --version
    register: php_version_check

  - name: Show the currently installed PHP version
    debug: 
      var: php_version_check.stdout_lines

  - name: Change templates_c directory ownership permissions to be only open for www-data user
    shell: cd /home/ubuntu/public_html && sudo find templates_c/ -type d -exec chown www-data:www-data '{}' ';'

  - name: Restart PHP 7.2 service
    shell: systemctl restart php7.2-fpm

  - name: Restart NGINX service
    shell: systemctl restart nginx

  - name: Restart Redis service
    shell: systemctl restart redis

  - name: Clear Redis cache
    shell: redis-cli flushall

  - name: Update Service Facts
    service_facts:

  - name: Check if PHP 7.2 is in running state - after restart    
    shell: systemctl status php7.2-fpm
    ignore_errors: yes

  - name: Show the PHP 7.2 state - after restart
    debug: 
      msg: "{{ansible_facts.services['php7.2-fpm.service'].state}}"

  - name: Check if NGINX is in running state - after restart    
    shell: systemctl status nginx
    ignore_errors: yes

  - name: Show the NGINX state - after restart
    debug: 
      msg: "{{ansible_facts.services['nginx.service'].state}}"

  - name: Check if Redis is in running state - after restart    
    shell: systemctl status redis
    ignore_errors: yes

  - name: Show the Redis state - after restart
    debug: 
      msg: "{{ansible_facts.services['redis-server.service'].state}}"

  - name: Check if all background tasks are up and running
    command: supervisorctl status
    register: tasks_status_check

  - name: Show the status of the background tasks
    debug: 
      var: tasks_status_check.stdout_lines

  - name: Restart all tasks which are in STOPPED, FATAL or STARTING state
    when: tasks_status_check.stdout_lines | regex_search(item)
    with_items:
      - "STOPPED"
      - "FATAL"
      - "STARTING"
    shell: supervisorctl restart all

  - name: Check if all background tasks are up and running - after restart
    command: supervisorctl status
    register: restarted_tasks_status_check
  
  - name: Show the status of the background tasks
    debug: 
      var: restarted_tasks_status_check.stdout_lines

  - name: Add the line in NGINX config file for maintenance on/off mode
    lineinfile: 
      path: /etc/nginx/sites-available/default
      insertafter: 'server {'
      line: '        set $maintenance on;'

  - name: Add a section in NGINX config which will redirect all the traffic to the maintenance page except DBP VPN IP address
    blockinfile: 
      path: /etc/nginx/sites-available/default 
      backup: yes 
      insertbefore: 'location / {' 
      block: |
           if ($remote_addr ~ (23.23.65.47)) {
               set $maintenance off;
           }

           if ($maintenance = on) {
               return 503;
           }

           error_page 503 @maintenance;

           location @maintenance {
               rewrite ^(.*)$ /502.html break;
           }

  - name: Check if NGINX configuration syntax is correct after the changes
    shell: nginx -t
    register: check_maintenance_nginx_syntax

  - name: Result of checking NGINX configuration syntax
    debug: 
      var: check_maintenance_nginx_syntax.stderr_lines

  - name: Restart NGINX service to apply the changes
    shell: systemctl restart nginx

  - name: Restart Redis service
    shell: systemctl restart redis

  - name: Restart PHP 7.2 service
    shell: systemctl restart php7.2-fpm

  - name: Clear Redis cache
    shell: redis-cli flushall

  - name: Update Service Facts
    service_facts:

  - name: Check if NGINX service is in running state - after restart    
    shell: systemctl status nginx
    ignore_errors: yes

  - name: Show the NGINX service state - after restart
    debug: 
      msg: "{{ansible_facts.services['nginx.service'].state}}"

  - name: Check if Redis is in running state - after restart    
    shell: systemctl status redis
    ignore_errors: yes

  - name: Show the Redis state - after restart
    debug: 
      msg: "{{ansible_facts.services['redis-server.service'].state}}"

  - name: Check if PHP 7.2 is in running state - after restart    
    shell: systemctl status php7.2-fpm
    ignore_errors: yes

  - name: Show the PHP 7.2 state - after restart
    debug: 
      msg: "{{ansible_facts.services['php7.2-fpm.service'].state}}"

  - name: Check if all background tasks are up and running
    command: supervisorctl status
    register: tasks_status_check

  - name: Show the status of the background tasks
    debug: 
      var: tasks_status_check.stdout_lines

  - name: Restart all tasks which are in STOPPED, FATAL or STARTING state
    when: tasks_status_check.stdout_lines | regex_search(item)
    with_items:
      - "STOPPED"
      - "FATAL"
      - "STARTING"
    shell: supervisorctl restart all

  - name: Check if all background tasks are up and running - after restart
    command: supervisorctl status
    register: restarted_tasks_status_check
  
  - name: Show the status of the background tasks
    debug: 
      var: restarted_tasks_status_check.stdout_lines
